server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-17f92e09-quantitymeasurement-app.c.aivencloud.com}:${DB_PORT:11428}/${DB_NAME:defaultdb}?useSSL=true&trustServerCertificate=true
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 28705293733-rp2kfvnhktufvu229nkfctnbr680htu1.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: 9a4f2c8d3e7b1a5c6d8e0f1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
  expiration: 86400000
