server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: conversion-service
          uri: lb://conversion-service
          predicates:
            - Path=/conversion/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
eureka:
  client:
    service-url:
      defaultZone: https://eureka-service-qpx1.onrender.com/eureka/
jwt:
  secret: 9a4f2c8d3e7b1a5c6d8e0f1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
