server:
  port: ${PORT}
spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:api-gateway/.env[.properties]
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_URL}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: conversion-service
          uri: lb://conversion-service
          predicates:
            - Path=/conversion/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: frontend-service
          uri: ${FRONTEND_URL}
          predicates:
            - Path=/**
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${eureka_url}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS}
    non-secure-port-enabled: ${EUREKA_NON_SECURE_PORT_ENABLED}
    secure-port-enabled: ${EUREKA_SECURE_PORT_ENABLED}
    secure-port: ${EUREKA_SECURE_PORT}
jwt:
  secret: ${jwt_secret}
