spring.application.name=quantity-measurement-backend

# DATABASE CONFIG

spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA CONFIG

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# SERVER CONFIG

server.port=8080

# Google OAuth2 Client Configuration (Placeholder/Default for UC18)
spring.security.oauth2.client.registration.google.client-id=28705293733-rp2kfvnhktufvu229nkfctnbr680htu1.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT Configuration
jwt.secret=9a4f2c8d3e7b1a5c6d8e0f1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
jwt.expiration=86400000